### ISSUE TITLE
[NEW] Tabs

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#266]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/1.1-Platform-Shared-Style-Library?node-id=534%3A0

**Comment by rohmad-st** [comment]
Izin mengambil issue yang ini yaa.. bro @resir014 
Sebentar lagi ane bikin PR

**Comment by resir014** [comment]
Oke, silakan @rohmad-st.
