### ISSUE TITLE
import react

### ISSUE THREAD

**Issue by wdavidcalsin** [kata-ai/aksara-ui#323]
https://github.com/kata-ai/aksara-ui/blob/a1244c2c84859fb701537dea151ac3b4ccd062f0/packages/aksara-icons/src/chart/IconChartGraph.tsx#L1

Wouldn't it be better to call react this way?
Because in a post I read that the correct way to call react is this.
~~~jsx
import * as React from 'react'
~~~

**Comment by resir014** [comment]
@wdavidcalsin Yeah, I used an automatic svg -> react converter to generate the icon files. Will have to look through them again and redo the exports.
