### ISSUE TITLE
[UPDATE] Button

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#367]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Dekstop-UI-KIT?node-id=139%3A288

### Additional Info

- Button borders are now 8px (lg)
- Variants are still the same, slightly tweaked colors.
- Icons now only on the left (deprecate `iconPosition="right"`)
- New `outline-destructive` variant

**Comment by neveraemje** [comment]
- Missed disclosure variant
- Missed disclosure plain variant

**Comment by treecore** [comment]
@neveraemje button udah okey menurutku. Disclosure & disclosure plain available
