### ISSUE TITLE
[UPDATE] Card

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#390]

**Comment by neveraemje** [comment]
- Missed disclosure variant
- Missed disclosure plain variant

**Comment by resir014** [comment]
@neveraemje done. please check again.

**Comment by neveraemje** [comment]
![image](https://user-images.githubusercontent.com/11992357/133381487-33103dd8-0ac8-419f-ba43-1f45b46f3cbc.png)
avatar di with piils using medium size.

**Comment by neveraemje** [comment]
Change border radius to be 8px. @zanuarmirza
