### ISSUE TITLE
[UPDATE] Pills

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#393]

**Comment by treecore** [comment]
- New update utk pills, versi icon didepan
- Kurang yg varian disable
- Padding antara text dan icon 4px

**Comment by neveraemje** [comment]
type pills with icon replace dengan image logo ya. udah dimention di figma comment.

**Comment by treecore** [comment]
20210920 revisions:
**default varian**
- background #E5EAEF
- Text #313F4E
- Close icon #313F4E
- Logo sample pake messenger channels

**Comment by neveraemje** [comment]
- basic example state ga bisa 

![image](https://user-images.githubusercontent.com/11992357/134100401-712d746a-356d-40ae-bfee-3c13328a3ba0.png)

- icon closable using 12 px.

**Comment by treecore** [comment]
@neveraemje pills udah okey menurutku.
Utk yg icon svg custom nanti dari FE yg nge-handle pills di page2 Kata OS.
