### ISSUE TITLE
[UPDATE] Modal

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#417]
https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=9192%3A39418

Page: Modal

**Comment by treecore** [comment]
@resir014 modal nya ini bisa diatur bebas kan width nya?

**Comment by neveraemje** [comment]
overlay modal using a combination with blur. check figma ya @resir014

**Comment by neveraemje** [comment]
Border radius change to be 8px

@zanuarmirza
