### ISSUE TITLE
[NEW] Navigation

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#418]
## Tasks

- [x] #432
- [x] #433

**Comment by neveraemje** [comment]
Done mas @treecore

**Comment by neveraemje** [comment]
Adding sidebar collapse & expand
refers design on figma https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=9228%3A2945

@resir014 @zanuarmirza

**Comment by zanuarmirza** [comment]
issue ##611
