### ISSUE TITLE
[UPDATE] Toast

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#421]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=9157%3A38227

**Comment by neveraemje** [comment]
- Missed variant processing and Error
- Space between items using 24 px

**Comment by neveraemje** [comment]
- total high single line 48px
- space between element must 24px

**Comment by treecore** [comment]
Toast mantap! cc: @neveraemje
