### ISSUE TITLE
[UPDATE] Table

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#429]

**Comment by neveraemje** [comment]
we have many variant cell item, how about that? 

cc @treecore @resir014

**Comment by neveraemje** [comment]
- missed sorted in header
- height cell / row fixed must be 48px
- avatar using small size
- channel using logo brand not icon. and the size must be small (same like avatar). you can take the logo ini brand library
- button on agent using small size
- teh status badge must be hug 

![image](https://user-images.githubusercontent.com/11992357/140002055-250833e6-d17b-47dc-af7b-3948fcc267c6.png)

@stevenevan @zanuarmirza
