### ISSUE TITLE
[UPDATE] Top Bar

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#430]

**Comment by neveraemje** [comment]
- Active button belum ada
- Missed online / offline button
- Missed variant logo only. 
- Give sample with notification count

@resir014

**Comment by neveraemje** [comment]
total notif info pake size 12x12px. font size 8px

@zanuarmirza @resir014

**Comment by neveraemje** [comment]
- Replace avatar and button icon to be avatar presence in Top Bar

@zanuarmirza

**Comment by zanuarmirza** [comment]
### Update story
_24 Nov 2021_
- [ ] use same height betweekn workspace button, online button, and round button

**Comment by neveraemje** [comment]
tambahin border bottom @zanuarmirza

**Comment by neveraemje** [comment]
adding logo
@zanuarmirza

**Comment by neveraemje** [comment]
logo using size 32px
