### ISSUE TITLE
[UPDATE] Pagination

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#431]
## Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=1641%3A0

## Additional Context

Only for base Pagination & `PaginationDetail`. `PaginationFilter` will be tracked on a separate issue.

## Tasks

- [x] Restyle pagination to follow new theming.
- [x] New `PaginationDetail` component. (`Showing xxx-xxx out of xxx`)
- [ ] #462 
- [ ] #534

**Comment by treecore** [comment]
@DioSyahrizal udah bikin style pagination terbaru di business dashboard; coba di review dan di merge @resir014

**Comment by neveraemje** [comment]
Check Figma design ya. Overall, about color, state, and layout, do not refer to Figma.

**Comment by neveraemje** [comment]
- Border radius using 8px
- Missed hovered state
- Missed item per page feature
- Pagination only has one variant. please recheck Figma,

**Comment by zanuarmirza** [comment]
## Need Adjustment
- [ ] Hover pagination button style
- [ ] Space 4px
