### ISSUE TITLE
[UPDATE] Typography

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#443]
### Figma Link

https://www.figma.com/file/Sv466903FX6euSUzYnc8OL/Desktop-Foundation?node-id=48%3A8

### Additional Info

**Heading**

![image](https://user-images.githubusercontent.com/5663877/132286653-11bf7fbd-bdf5-4cad-aab7-500b561d7a87.png)

**Text**

![image](https://user-images.githubusercontent.com/5663877/132286670-dcbafcd3-37b9-46d0-ba7d-bb25de8d81d9.png)

**Comment by neveraemje** [comment]
adding button label, input label & caption

**Comment by neveraemje** [comment]
missed button label, input label & caption

**Comment by treecore** [comment]
20210920, revisions @resir014 :

- Body text 500 belum ada
- Body text 200 belum ada
- Button label belum ada
- Label belum ada
- Caption belum ada
