### ISSUE TITLE
[UPDATE] Date picker

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#444]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=2748%3A0

### Additional Info

- Rewrite date picker with [dayzed](https://github.com/deseretdigital/dayzed).
- Single date + date range picker

## Component
- [x] Date Number Component
- [x] Date Picker Container
- [x] Date Picker Input  

### Date Picker
variant: 
- [x] Single
- [x] Range
- [x] Advance

### Story
- [x] add example using input text

#### Picker
- [x] when click date, handlerPicker is called

#### Range Picker
- [x] value range picker selected
- [x] value index 0 must be < value of index 1
- [x] value index 0 is start, value index 1 is end
- [x] select same start and end date
- [x] when updateButton click, handlerPicker is called
#### AdvancedDateRangePicker
- [x] when click option,optionhandler is called
- [x]  when updateButton click, handlerPicker is called

**Comment by neveraemje** [comment]
- Delete story multiple date
- Button di multiple date and advance using medium size
- Advance date picker using range function 

@zanuarmirza

**Comment by neveraemje** [comment]
- advance date picker when selected option,range style unmatched with our style
- space between date and button too light
- Revision on textfield not yet solving. 

@zanuarmirza
