### ISSUE TITLE
[UPDATE] Form / Text

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#447]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=140%3A0

### Tasks

- [ ] #406
- [ ] #405
- [ ] #400
- [ ] #403
- [ ] #404

**Comment by treecore** [comment]
@resir014 revisi untuk InputText & Helper:
Tolong di-revisi hari ini, dan mention aq kalo udah selesai.

**InputMessage (Helper):**
	▪	Line heightnya adalah 18px bukan 16px
	▪	Font varian adalah MEDIUM bukan REGULAR
	▪	Varian Warning; Yellow nya BUKAN DBA800 TAPI A37D00
	▪	Varian Critical; Icon nya SALAH


**InputText:**
	▪	Size input Medium 32px bukan 30px
	▪	Size input Large 40px bukan 38px
	▪	Border radius 1px warnanya BUKAN B0B7BF tapi C6D0DB
	▪	Text dalam input fieldnya gak center! https://prnt.sc/1tanvw6
	▪	Text dalam input yg active (typing/filling) warnanya bukan 34404D tapi 313F4E
	▪	Input field state active (typing) border radius 1px warnanya bukan 2A71DE tapi 3797FF
	▪	Input field state active (typing) border radius 2px outside warnanya bukan C0D4F5 tapi AFD6FF (70%)
	▪	Error state; border radius 1px warnanya bukan EE6C59 tapi FF6150
	▪	Input field varian suffix/prefix; Text suffix dan prefix warnanya bukan 6D7B88 tapi 6A7A8A
	▪	Input field varian suffix/prefix; di disable state text suffix dan prefix warnanya bukan B1B7BE tapi B0B7BF
	▪	Input field varian suffix/prefix; di disable state text input fieldnya warnanya bukan B1B7BE tapi B0B7BF
	▪	Input field varian suffix/prefix; text suffix/prefix dengan input field nya tidak center
	▪	Input field varian with icon; warna iconnya bukan 6D7B88 tapi 6A7A8A
	▪	Input field varian with icon; di disable state warna iconnya bukan B1B7BE tapi B0B7BF

@resir014 tolong lebih teliti lagi dan liat detail Figmanya, jadi kesalahan2 seperti warna, size dan padding bisa diminimalisir.

**Comment by treecore** [comment]
@resir014 revisi lagi,
**InputMessage (Helper):**

- Varian Warning dan Info beda warna antara icon dan text (mentioned in Figma & Slack) https://prnt.sc/1tblybd

**InputText:**
Active/Typing state; masih belum berubah (atas comp. library; bawah design)https://prnt.sc/1tbm5cm
▪ Input field state active (typing) border radius 1px warnanya bukan 2A71DE tapi 3797FF
▪ Input field state active (typing) border radius 2px outside warnanya bukan C0D4F5 tapi AFD6FF (70%)
