### ISSUE TITLE
[NEW] Form / Select Field

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#451]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=10283%3A26667

Page: Form - Select Field

### Additional Info

Wrapper for [Downshift](https://www.downshift-js.com/) which adds a Select input with our design guidelines.

## Tasks

- [x] Select
- [x] Combobox

**Comment by neveraemje** [comment]
**Select Tag**
- filled state outline sama seperti default (bukan blue) / (benchmark dari select search udah oke)
- Apakah possible saat pilih select field muncul semua isi droprown tanpa harus searching dulu? 

**Select Search**
- Apakah possible saat pilih select field muncul semua isi droprown tanpa harus searching dulu? 

**Select**
- border State focus and active belum sesuai. (benchmark dari select search udah oke)

@IzzanNurdin @DioSyahrizal @resir014

**Comment by neveraemje** [comment]
- Input select pake padding 12 px
@zanuarmirza

**Comment by neveraemje** [comment]
Padding kanan 12 px @zanuarmirza
