### ISSUE TITLE
[NEW] Pagination / PaginationFilter

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#462]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=1641%3A0

### Additional Info

Separate from #431. This is meant for the filter selector on the right side of the pagination.

**Comment by zanuarmirza** [comment]
### TODO
_01 Des 2021_

- [ ] filter using dropdown

**Comment by neveraemje** [comment]
- Dropdown item follow action list item
- Adding Nubbin

@zanuarmirza
