### ISSUE TITLE
[UPDATE] Dropdown List

### ISSUE THREAD

**Issue by treecore** [kata-ai/aksara-ui#492]
### Figma
https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=9113%3A272

## Spec
_1 Des 2021_
- [ ] Dropdown List add Action button footer
- [x] Border radius using 8px
- [x] DropdownList = wrap action list + nubbin
- [x] Dropdown item will be using button (ActionListItem as Button)
- [x] When using keyboard, use focus to show highlighted item
- [x] When using mouse, use hover to show highlighted item

**Comment by neveraemje** [comment]
- Dropdown List add Action button footer
@zanuarmirza

**Comment by neveraemje** [comment]
- Separator full
- Space tiap item 2px
- Focus and active state belum ada
- Selected state belum sesuai. font warna biru and border ujung belum sesuai. 

@zanuarmirza

**Comment by neveraemje** [comment]
Space between trigger action with dropdown 4px. 
@zanuarmirza

**Comment by neveraemje** [comment]
space each item must be 4px. @zanuarmirza

**Comment by neveraemje** [comment]
- Nubbin position ambil dari popover
