### ISSUE TITLE
Avatar Presence

### ISSUE THREAD

**Issue by neveraemje** [kata-ai/aksara-ui#566]
### Figma Link

https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=560%3A0

**Comment by zanuarmirza** [comment]
## Avatar Presence

- Wide Maximum 24 px
- Size 12 px
- Add Position Button at Storybook
- Avatar use  box-sizing: border-box
- Presence use  box-sizing: content-box
- presence large 1 digit pake ratio1:1 padding 2px box size total 12 px
- presence small 1 digit pake ratio 1:1 padding 1 px, box size total 10px
- present presence bottom story
### TODO
- [ ] avatar presence
- [ ] unit test
