### ISSUE TITLE
List Resource

### ISSUE THREAD

**Issue by neveraemje** [kata-ai/aksara-ui#568]
### Figma Link
https://www.figma.com/file/R7ymwKrEI3LF6ssrZe5opG/Desktop-UI-Kit?node-id=9544%3A40352

### reference 
https://polaris.shopify.com/components/lists-and-tables/resource-list#navigation

### TODO
- [x] add stories 
     - [x]  with select
     - [x]  header when item selected

**Comment by neveraemje** [comment]
**List item**
- adding border in selected state
- text on list using size 14 or body 300


**Header**
- when selected selected info using font body 300 / 14px
- when selected the button using size small
- size height header using fixed 40px

@zanuarmirza

**Comment by zanuarmirza** [comment]
### Review
_17 Des 2021_
- [ ] selected item color Text/Primary - @greydark-02
