### ISSUE TITLE
[UPDATE] Contextual Save Bar

### ISSUE THREAD

**Issue by neveraemje** [kata-ai/aksara-ui#695]
use Portal for Contextual Save Bar.
Contextual Save Bar always takes position at the top of the page.

**Comment by neveraemje** [comment]
I think the transformation when the to save-bar appears too stiff. I there possible we have` dissolve animation` when the save-bar appears. @zanuarmirza

**Comment by zanuarmirza** [comment]
okay
will use fade in and fade out for the enter and leave transition
