### ISSUE TITLE
[PaginationDetail] Shows the max items per page even if number of items is less than items per page

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#698]
## Description

If the `total` value is less than `limit`, the `PaginationDetail` still displays "Showing 1-`limit` of `total` items", instead of "Showing 1-`total` of `total` items".

![image](https://user-images.githubusercontent.com/5663877/148881784-d0c17499-3407-4541-9f35-60c40d82a83c.png)

### Expected result

Pagination should show correctly even if the number of items is below items per page.

### Steps to reproduce

- Create a pagination list with 10 items per page
- Add list items less than the defined amount of items per page

**Comment by zanuarmirza** [comment]
## TODO
- [ ] fix total values 
- [ ] unit test
