### ISSUE TITLE
PaginationFilter dropdown not placed properly and must press hold to show dropdown

### ISSUE THREAD

**Issue by IzzanNurdin** [kata-ai/aksara-ui#715]
## Description

`PaginationFilter` dropdown location not located properly and not toggled, must pressed hold.

![image](https://user-images.githubusercontent.com/21364861/149460710-52aeca6b-a5fa-4968-97e3-30498ee566e8.png)

### Expected result

Dropdown located properly based on `aside` props and toggle on open dropdown

**Comment by zanuarmirza** [comment]
@IzzanNurdin 
can you make sample code to reproduce this bug ?

**Comment by zanuarmirza** [comment]
make sure dont use margin top at body level or outer layout. use padding-top instead
