### ISSUE TITLE
[BUG] Accordion icon is not consistent when there is 2 or more lines text

### ISSUE THREAD

**Issue by stevenevan** [kata-ai/aksara-ui#723]
## Description

Icon size will be shrunk when the text is too long (2 lines or more)

### Actual result

![image](https://user-images.githubusercontent.com/50607674/149883472-98a6e86b-f3a4-435f-ad7d-0d0d9365e2a2.png)

### Expected result

All icons has same size.

![image](https://user-images.githubusercontent.com/50607674/149883369-ed82b6e9-9bdd-4665-b683-21fb29234c58.png)

**Comment by zanuarmirza** [comment]
https://aksara.kata.ai/?path=/story/core-components-accordion--single-accordion
has 2 line content buy icon size still same.
can you check again why it shrinks like that by referencing the code from storybook?

**Comment by stevenevan** [comment]
It has been fixed in the newer version canary. Thanks.

Btw, maybe we should include the actual result and package's specification to identify the problem efficiently.

- Description
- Actual Result
- Expected Result
- Specification
   - @aksara-ui/react: 
   - @aksara-ui/core
   - etc
- Steps to reproduce
