### ISSUE TITLE
[BUG] Accordion has black outline above the focus state style

### ISSUE THREAD

**Issue by stevenevan** [kata-ai/aksara-ui#724]
## Description

The focus state in the accordion header is overwritten by the black outline.

![image](https://user-images.githubusercontent.com/50607674/149884303-2bb50d1c-19cf-4ad5-a7af-59bd6900fabe.png)

### Expected result

There is no black outline on the accordion header's focus state.

![image](https://user-images.githubusercontent.com/50607674/149884517-d7fbb67e-1fe0-4be8-8efd-6d04a07d688c.png)

### Steps to reproduce

```JSX
  <Accordion type="multiple">
      <AccordionItem key={item.title} value={item.title}>
        <AccordionHeader size="lg">
          <TocText>{item.title}</TocText>
        </AccordionHeader>
        {item.items.map((itemChildern) => {
          return (
            <AccordionContent key={itemChildern.title}>
              <TocAnchor href={itemChildern.url}>{itemChildern.title}</TocAnchor>
              {itemChildern.items?.length ? <TocJsonWrapper tree={itemChildern} /> : null}
            </AccordionContent>
          );
        })}
      </AccordionItem>
</Accordion>
```

**Comment by zanuarmirza** [comment]
check canary 26
accordion story has been updated for this case
